### ISSUE TITLE
ifconfig.status doesn't work

### ISSUE THREAD

**Issue by MikeWar1ock** [bakerface/wireless-tools#51]
Hi, im using from **documentation**:
``` javascript
var ifconfig = require("wireless-tools/ifconfig");

ifconfig.status(function(err, status) {
  console.log(err);
});
```
**And what i have**:
 _Error: Command failed: iwconfig
'iwconfig' is not recognized as an internal or external command,
operable program or batch file._

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5) killed: false, code: 1, signal: null, cmd: 'iwconfig' }

Whats wrong with this?

**Comment by lesmo** [comment]
Are you running it in a Linux environment? The ```iwconfig``` command this package runs is not available on Windows or Mac.
